config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :lists
  resources :items
  root "lists#index"

  get "/lists", to: "lists#index"
  get "/lists/new", to: "lists#new" , as:"new_list"
  get "/lists/:id", to: "lists#show" , as: "list"
  get "/items", to: "items#show"
  get "/lists/:id/edit", to:"lists#edit" ,as:"edit_list"


  get "/lists/:id/new_item", to: "item#new_item"
  

  post "/lists", to: "lists#create"
  post "/items", to: "items#create"

  patch "/lists/:id", to: "lists#update"

  delete "/lists/:id", to: "lists#destroy"
  delete "/item/:id", to: "items#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
  
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_list
  def new_item
    @item = Item.new
  end

  def show

  end

  def create
    #logger.debug "id============================ #{params[:id]}
    @item = Item.new(item_params)
    if @item.save
      redirect_to lists_path
    else
      render :new_item, status: :unprocessable_entity
    end

  end

  def set_list
    temp = params[:list_id]
    #temp = temp.to_i
    @list = current_user.lists.find_by(id: temp)
    #redirect_to lists_path if @list.blank?
  end

  def item_params
    params.require(:item).permit(:content, :list_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_list
  def new
    @item = Item.new
  end

  def show

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def destroy
    set_item
    @item&.destroy
    redirect_to lists_path
  end

  def set_list
    temp = params[:list_id]
    #temp = temp.to_i
    @list = current_user.lists.find_by(id: temp)
    #redirect_to lists_path if @list.blank?
  end

  def set_item
    @item = Item.find_by(id: params[:id])
  end

  def item_params
    params.require(:item).permit(:content, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!


  def index
    @lists = current_user.lists.order(created_at: :desc)
  end

  def show
    set_list
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      session[:id] = @list.id
      redirect_to new_item_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def destroy
    set_list
    @list.destroy
    redirect_to lists_path
  end

  def edit
    set_list
  end

  def update
    set_list
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def set_list
    @list = current_user.lists.find_by(id: params[:id])
    redirect_to lists_path if @list.blank?
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/new.html.erb
<div class="w-full h-full flex justify-center flex-col items-center">
    <%= simple_form_for @item do |f| %>
        <div class="flex justify-center flex-col p-10 bg-white w-[400px] rounded-lg">
            <h1 class="flex items-center justify-center text-2xl">Editando Lista</h1>
            <div class="form-inputs space-y-4">
                <%= f.label :conteudo, class: "block text-gray-700 text-sm font-bold mb-2"%>
                <%= f.input :content, 
                            label:false,
                            input_html: { class: "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }
                %>
                <% @id = session[:variavel] %>
                <%= f.input :list_id, as: :hidden , 
                input_html:{value: session[:id], readonly:true}%>
                <%= f.button :submit, "Adicionar ",
                class:"cursor-pointer bg-red-300 px-5 rounded mt-[10px]"
                %>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#f7bce6]">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="w-full h-full flex justify-center flex-col items-center">
    <%= simple_form_for @list do |f| %>
        <div class="flex justify-center flex-col p-10 bg-white w-[400px] rounded-lg">
            <div class="form-inputs space-y-4">
                <%=f.label :titulo, class: "block text-gray-700 text-sm font-bold mb-2"%>
                <%= f.input :title, 
                            label:false
                %>
                
                <%= f.button :submit%>
            </div>
        </div>
    <% end %>
</div>

app/views/lists/edit.html.erb
<h1>Editando Lista</h1>
<%= render partial: "form" %>

app/views/lists/index.html.erb
<head>
    <style>
        .custom-button{
            background-color: #f7547a;
            color:white;
            padding:1px 2px;
            border:none;
            border-radius: 5px;
            cursor:pointer;
        }
    </style>
</head>
<center>
<font size="+5">
        <h1 class="font-['Open_Sans'] text-white bg-red-400 w-[300px] rounded-lg">
            TODO List
        </h1>
</font>
<% if user_signed_in? %>
    <p style="color:#f7547a" onmouseover="this.style.color='green';" onmouseout="this.style.color='#f7547a'">
        <%= link_to "Nova lista", new_list_path %>
    </p>
    <%= button_to "Deslogar", destroy_user_session_path, method: :delete , class: "custom-button"%>
<% end %>

    
<% @lists.each do |list|%>
    <div class="inline-flex items-baseline">
        <div class=" mx-0 flex flex-col p-10 bg-white w-[300px] min-h-[50px] h-[auto] mt-[50px] rounded-lg " >
            <h2 style="color:#f7547a" onmouseover="this.style.color='#73c6fa';" onmouseout="this.style.color='#f7547a'">
                <u>
                    <font size="+2">
                        <%= link_to(list.title, list_path(list)) %>
                    </font>
                </u>
            </h2>
            <div>
                <% list.items.each do |item| %>
                <div>
                    <input type="checkbox">
                    <span>
                        <%= item.content %>
                    </span>
                    <%= button_to "Deletar", item_path(item), method: :delete, class: "custom-button" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
<%end%>
</center>

app/views/lists/new.html.erb
<div class="w-full h-full flex justify-center flex-col items-center">
    <%= simple_form_for @list do |f| %>
        <div class="flex justify-center flex-col p-10 bg-white w-[400px] rounded-lg">
            <h1 class="flex items-center justify-center text-2xl">Nova Lista</h1>
            <div class="form-inputs space-y-4">
                <%=f.label :titulo, class: "block text-gray-700 text-sm font-bold mb-2"%>
                <%= f.input :title, 
                            label:false,
                            input_html: { class: "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }
                %>
                <%session[:id] = @list.id%> <!--Salvando id da lista-->
                <%= f.button :submit, "Criar",
                              class:"cursor-pointer bg-red-300 px-5 rounded mt-[10px]"
                %>
                <div class="left">
                <%= link_to "Criar Item", new_item_path %>
                </div>
            </div>
        </div>
    <% end %>
</div>
<!--<%= render partial: "form" %>-->


    

app/views/lists/show.html.erb
<head>
    <style>
        .custom-button{
            background-color: #f7547a;
            color:white;
            padding:1px 2px;
            border:none;
            border-radius: 5px;
            cursor:pointer;
        }
    </style>
</head>
<center>
    <div class="flex justify-center flex-col p-10 bg-white w-[300px] min-h-[50px] h-[auto] mt-[50px] rounded-lg " >
        <font size="+3">
                <h1><%= @list.title %></h1>
        </font>
        <% if user_signed_in? %>
            <p style="color:#f7547a" onmouseover="this.style.color='green'; "onmouseout="this.style.color='#f7547a'">
                <%= link_to "Editar", edit_list_path(@list) %>
            </p>

            <%= button_to "Deletar", list_path(@list), method: :delete, class: "custom-button" %>
        <% end %>
        <% @list.items.each do |item| %>
            <p>
                <%= item.content %>
            </p>
        <% end %>
        <div class="mt-[40px]"style="color:#f7547a" onmouseover="this.style.color='green'; "onmouseout="this.style.color='#f7547a'">
            <%= link_to "Voltar", lists_path%>
        </div>
    </div>
</center>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Login", new_session_path(resource_name),class:"text-teal-800 text-center mt-[10px] " %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Inscreve-se", new_registration_path(resource_name), class:"text-teal-800 text-center mt-[10px] " %><br/>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esquece sua senha?", new_password_path(resource_name), class:"text-teal-800 text-center" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>